
-- 1. Ensure Enums Exist
DO $$ begin
    create type public.delivery_method as enum ('pickup', 'delivery');
exception
    when duplicate_object then null;
end $$;

DO $$ begin
    create type public.order_status as enum ('pending', 'preparing', 'out_for_delivery', 'completed', 'cancelled');
exception
    when duplicate_object then null;
end $$;

-- 2. CREATE Tables (If they don't exist at all)
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon_name text not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. MIGRATE Tables (Add columns if they exist but match old schema)

-- Products Migration
alter table public.products add column if not exists stock_quantity int not null default 0;
alter table public.products add column if not exists min_stock_alert int not null default 5;
alter table public.products add column if not exists category_id bigint references public.categories(id) on delete set null;
alter table public.products add column if not exists images_url text[] default array[]::text[];
alter table public.products add column if not exists average_rating decimal(3,2) default 0.00;
alter table public.products add column if not exists status boolean default true;

-- Orders Table (Create if missing, unlikely to exist in old schema but good to be safe)
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  customer_data jsonb not null,
  delivery_method public.delivery_method not null,
  delivery_fee numeric(10,2) default 0.00,
  total_price numeric(10,2) not null,
  status public.order_status default 'pending',
  items jsonb not null, 
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Reviews Table
create table if not exists public.reviews (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references public.products(id) on delete cascade not null,
  author_name text not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  is_verified boolean default false,
  created_at timestamptz default now()
);

-- 4. POLICIES (Drop and Recreate to ensure they use the new columns)

-- Products Policies
drop policy if exists "Allow Public Read Active Products" on public.products;
create policy "Allow Public Read Active Products" on public.products for select using (status = true);

drop policy if exists "Allow Admin Full Access Products" on public.products;
create policy "Allow Admin Full Access Products" on public.products using (auth.role() = 'authenticated');

-- Categories Policies
alter table public.categories enable row level security;
drop policy if exists "Allow Public Read Categories" on public.categories;
create policy "Allow Public Read Categories" on public.categories for select using (true);
drop policy if exists "Allow Admin Full Access Categories" on public.categories;
create policy "Allow Admin Full Access Categories" on public.categories using (auth.role() = 'authenticated');


-- 5. SEED Categories (Idempotent)
insert into public.categories (name, slug, icon_name) values
('Cabelo', 'cabelo', 'Scissors'),
('Barba', 'barba', 'User'),
('Kits', 'kits', 'Package'),
('Acessórios', 'acessorios', 'Grid')
on conflict (slug) do nothing;
