
-- EXTENSIONS
create extension if not exists "moddatetime" with schema "extensions";

-- ENUMS (Safe Creation)
DO $$ begin
    create type public.delivery_method as enum ('pickup', 'delivery');
exception
    when duplicate_object then null;
end $$;

DO $$ begin
    create type public.order_status as enum ('pending', 'preparing', 'out_for_delivery', 'completed', 'cancelled');
exception
    when duplicate_object then null;
end $$;

-- 1. PROFILES (Admin Management)
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade not null primary key,
  role text default 'admin' check (role in ('admin', 'staff')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 2. CATEGORIES
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  icon_name text not null, -- Lucide Icon Name
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists categories_slug_idx on public.categories (slug);

-- 3. PRODUCTS
create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  description text,
  price numeric(10,2) not null check (price >= 0),
  stock_quantity int not null default 0,
  min_stock_alert int not null default 5,
  category_id bigint references public.categories(id) on delete set null,
  images_url text[] default array[]::text[],
  average_rating decimal(3,2) default 0.00,
  status boolean default true, -- Active/Inactive
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 4. ORDERS
create table if not exists public.orders (
  id uuid default gen_random_uuid() primary key,
  customer_data jsonb not null, -- { name, phone, address? }
  delivery_method public.delivery_method not null,
  delivery_fee numeric(10,2) default 0.00,
  total_price numeric(10,2) not null,
  status public.order_status default 'pending',
  items jsonb not null, -- Snapshot of items bought
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 5. REVIEWS
create table if not exists public.reviews (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references public.products(id) on delete cascade not null,
  author_name text not null,
  rating int not null check (rating >= 1 and rating <= 5),
  comment text,
  is_verified boolean default false,
  created_at timestamptz default now()
);

-- ROW LEVEL SECURITY (RLS)

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.reviews enable row level security;

-- POLICIES (Drop first to allow re-run)

-- Categories
drop policy if exists "Allow Public Read Categories" on public.categories;
create policy "Allow Public Read Categories" on public.categories for select using (true);

drop policy if exists "Allow Admin Full Access Categories" on public.categories;
create policy "Allow Admin Full Access Categories" on public.categories using (auth.role() = 'authenticated');

-- Products
drop policy if exists "Allow Public Read Active Products" on public.products;
create policy "Allow Public Read Active Products" on public.products for select using (status = true);

drop policy if exists "Allow Admin Full Access Products" on public.products;
create policy "Allow Admin Full Access Products" on public.products using (auth.role() = 'authenticated');

-- Orders
drop policy if exists "Allow Public Create Orders" on public.orders;
create policy "Allow Public Create Orders" on public.orders for insert with check (true);

drop policy if exists "Allow Admin Full Access Orders" on public.orders;
create policy "Allow Admin Full Access Orders" on public.orders using (auth.role() = 'authenticated');

-- Reviews
drop policy if exists "Allow Public Read Reviews" on public.reviews;
create policy "Allow Public Read Reviews" on public.reviews for select using (true);

drop policy if exists "Allow Public Create Reviews" on public.reviews;
create policy "Allow Public Create Reviews" on public.reviews for insert with check (true);

drop policy if exists "Allow Admin Manage Reviews" on public.reviews;
create policy "Allow Admin Manage Reviews" on public.reviews using (auth.role() = 'authenticated');

-- TRIGGERS (Drop first)

drop trigger if exists handle_updated_at_profiles on public.profiles;
create trigger handle_updated_at_profiles before update on public.profiles
  for each row execute procedure moddatetime (updated_at);

drop trigger if exists handle_updated_at_categories on public.categories;
create trigger handle_updated_at_categories before update on public.categories
  for each row execute procedure moddatetime (updated_at);

drop trigger if exists handle_updated_at_products on public.products;
create trigger handle_updated_at_products before update on public.products
  for each row execute procedure moddatetime (updated_at);

drop trigger if exists handle_updated_at_orders on public.orders;
create trigger handle_updated_at_orders before update on public.orders
  for each row execute procedure moddatetime (updated_at);

-- SEED DATA (Use ON CONFLICT do nothing)
insert into public.categories (name, slug, icon_name) values
('Cabelo', 'cabelo', 'Scissors'),
('Barba', 'barba', 'User'),
('Kits', 'kits', 'Package'),
('Acessórios', 'acessorios', 'Grid')
on conflict (slug) do nothing;
